"""add chunk embeddings table

Revision ID: 08e7f1615d2b
Revises: 3e38f1b920b0
Create Date: 2026-08-27 23:37:43.832056

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '08e7f1615d2b'
down_revision: Union[str, None] = '3e38f1b920b0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chunk_embeddings',
    sa.Column('chunk_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('embedding', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['chunk_id'], ['document_chunks.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('chunk_id')
    )
    op.create_index(op.f('ix_chunk_embeddings_material_id'), 'chunk_embeddings', ['material_id'], unique=False)
    op.create_index(op.f('ix_chunk_embeddings_user_id'), 'chunk_embeddings', ['user_id'], unique=False)
    op.create_index('ix_chunk_embeddings_user_material', 'chunk_embeddings', ['user_id', 'material_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_chunk_embeddings_user_material', table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_user_id'), table_name='chunk_embeddings')
    op.drop_index(op.f('ix_chunk_embeddings_material_id'), table_name='chunk_embeddings')
    op.drop_table('chunk_embeddings')
    # ### end Alembic commands ###
