"""initial schema

Revision ID: 3e38f1b920b0
Revises: 
Create Date: 2026-08-27 23:31:33.789000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = '3e38f1b920b0'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('materials',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('filename', sa.String(length=512), nullable=False),
    sa.Column('file_type', sa.String(length=32), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('UPLOADED', 'PROCESSING', 'READY', 'FAILED', name='materialstatus', native_enum=False, length=32), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('storage_path', sa.String(length=1024), nullable=False),
    sa.Column('processing_error', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_materials_user_id'), 'materials', ['user_id'], unique=False)
    op.create_index('ix_materials_user_status', 'materials', ['user_id', 'status'], unique=False)
    op.create_table('topics',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_topics_user_id'), 'topics', ['user_id'], unique=False)
    op.create_index('ix_topics_user_name', 'topics', ['user_id', 'name'], unique=True)
    op.create_table('weaknesses',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('concept', sa.String(length=255), nullable=False),
    sa.Column('attempt_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('mistake_count', sa.Integer(), nullable=False),
    sa.Column('accuracy', sa.Float(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False, length=16), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_weaknesses_user_id'), 'weaknesses', ['user_id'], unique=False)
    op.create_index('ix_weaknesses_user_topic_concept', 'weaknesses', ['user_id', 'topic', 'concept'], unique=True)
    op.create_table('document_chunks',
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('page_number', sa.Integer(), nullable=True),
    sa.Column('section', sa.String(length=255), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_document_chunks_material_id'), 'document_chunks', ['material_id'], unique=False)
    op.create_index('ix_document_chunks_material_index', 'document_chunks', ['material_id', 'chunk_index'], unique=False)
    op.create_index(op.f('ix_document_chunks_user_id'), 'document_chunks', ['user_id'], unique=False)
    op.create_index('ix_document_chunks_user_material', 'document_chunks', ['user_id', 'material_id'], unique=False)
    op.create_table('quizzes',
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('material_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(length=512), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False, length=16), nullable=False),
    sa.Column('status', sa.Enum('GENERATING', 'READY', 'FAILED', name='quizstatus', native_enum=False, length=16), nullable=False),
    sa.Column('generation_error', sa.String(length=1024), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['material_id'], ['materials.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_quizzes_material_id'), 'quizzes', ['material_id'], unique=False)
    op.create_index('ix_quizzes_user_created', 'quizzes', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quizzes_user_id'), 'quizzes', ['user_id'], unique=False)
    op.create_table('questions',
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('question_type', sa.Enum('MULTIPLE_CHOICE', 'TRUE_FALSE', 'SHORT_ANSWER', name='questiontype', native_enum=False, length=32), nullable=False),
    sa.Column('question_text', sa.Text(), nullable=False),
    sa.Column('options', sa.JSON(), nullable=True),
    sa.Column('correct_answer', sa.Text(), nullable=False),
    sa.Column('explanation', sa.Text(), nullable=False),
    sa.Column('topic', sa.String(length=255), nullable=False),
    sa.Column('difficulty', sa.Enum('EASY', 'MEDIUM', 'HARD', name='difficulty', native_enum=False, length=16), nullable=False),
    sa.Column('source_reference', sa.Text(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_questions_quiz_id'), 'questions', ['quiz_id'], unique=False)
    op.create_index('ix_questions_quiz_order', 'questions', ['quiz_id', 'order_index'], unique=False)
    op.create_index(op.f('ix_questions_topic'), 'questions', ['topic'], unique=False)
    op.create_table('quiz_attempts',
    sa.Column('quiz_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='attemptstatus', native_enum=False, length=16), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_questions', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('incorrect_count', sa.Integer(), nullable=False),
    sa.Column('score', sa.Float(), nullable=True),
    sa.Column('accuracy', sa.Float(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['quiz_id'], ['quizzes.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_attempts_user_created', 'quiz_attempts', ['user_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_quiz_id'), 'quiz_attempts', ['quiz_id'], unique=False)
    op.create_index(op.f('ix_quiz_attempts_user_id'), 'quiz_attempts', ['user_id'], unique=False)
    op.create_table('answers',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('question_id', sa.String(), nullable=False),
    sa.Column('selected_answer', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=True),
    sa.Column('time_taken_seconds', sa.Float(), nullable=True),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_type', sa.Enum('CONCEPTUAL_MISUNDERSTANDING', 'KNOWLEDGE_GAP', 'CARELESS_MISTAKE', 'MISREAD_QUESTION', 'CONCEPT_CONFUSION', 'UNKNOWN', name='errortype', native_enum=False, length=32), nullable=True),
    sa.Column('misconception', sa.Text(), nullable=True),
    sa.Column('mistake_explanation', sa.Text(), nullable=True),
    sa.Column('severity', sa.Enum('LOW', 'MEDIUM', 'HIGH', name='severity', native_enum=False, length=16), nullable=True),
    sa.Column('recommended_action', sa.Enum('REVIEW_CONCEPT', 'PRACTICE_MORE', 'RE_READ_MATERIAL', 'SLOW_DOWN', 'NONE', name='recommendedaction', native_enum=False, length=32), nullable=True),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_answers_attempt_id'), 'answers', ['attempt_id'], unique=False)
    op.create_index('ix_answers_attempt_question', 'answers', ['attempt_id', 'question_id'], unique=True)
    op.create_index(op.f('ix_answers_question_id'), 'answers', ['question_id'], unique=False)
    op.create_table('summaries',
    sa.Column('attempt_id', sa.String(), nullable=False),
    sa.Column('user_id', sa.String(), nullable=False),
    sa.Column('content', sa.JSON(), nullable=False),
    sa.Column('raw_ai_response', sa.JSON(), nullable=True),
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['quiz_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_summaries_attempt_id'), 'summaries', ['attempt_id'], unique=True)
    op.create_index(op.f('ix_summaries_user_id'), 'summaries', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_summaries_user_id'), table_name='summaries')
    op.drop_index(op.f('ix_summaries_attempt_id'), table_name='summaries')
    op.drop_table('summaries')
    op.drop_index(op.f('ix_answers_question_id'), table_name='answers')
    op.drop_index('ix_answers_attempt_question', table_name='answers')
    op.drop_index(op.f('ix_answers_attempt_id'), table_name='answers')
    op.drop_table('answers')
    op.drop_index(op.f('ix_quiz_attempts_user_id'), table_name='quiz_attempts')
    op.drop_index(op.f('ix_quiz_attempts_quiz_id'), table_name='quiz_attempts')
    op.drop_index('ix_attempts_user_created', table_name='quiz_attempts')
    op.drop_table('quiz_attempts')
    op.drop_index(op.f('ix_questions_topic'), table_name='questions')
    op.drop_index('ix_questions_quiz_order', table_name='questions')
    op.drop_index(op.f('ix_questions_quiz_id'), table_name='questions')
    op.drop_table('questions')
    op.drop_index(op.f('ix_quizzes_user_id'), table_name='quizzes')
    op.drop_index('ix_quizzes_user_created', table_name='quizzes')
    op.drop_index(op.f('ix_quizzes_material_id'), table_name='quizzes')
    op.drop_table('quizzes')
    op.drop_index('ix_document_chunks_user_material', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_user_id'), table_name='document_chunks')
    op.drop_index('ix_document_chunks_material_index', table_name='document_chunks')
    op.drop_index(op.f('ix_document_chunks_material_id'), table_name='document_chunks')
    op.drop_table('document_chunks')
    op.drop_index('ix_weaknesses_user_topic_concept', table_name='weaknesses')
    op.drop_index(op.f('ix_weaknesses_user_id'), table_name='weaknesses')
    op.drop_table('weaknesses')
    op.drop_index('ix_topics_user_name', table_name='topics')
    op.drop_index(op.f('ix_topics_user_id'), table_name='topics')
    op.drop_table('topics')
    op.drop_index('ix_materials_user_status', table_name='materials')
    op.drop_index(op.f('ix_materials_user_id'), table_name='materials')
    op.drop_table('materials')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
